#### language: yaml
# version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: 12345678
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - blog-network

  blog:
    build: ../
    container_name: blog
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: testuser
      DATABASE_PASSWORD: 12345678
      DATABASE_DB: test
    depends_on:
      - mysql
    ports:
      - '4356:4356'
      - '80:80'
      - '443:443'
      - '6060:6060'
    networks:
      - blog-network

volumes:
  mysql-data:

networks:
  blog-network:
